# GitHub Pages 配置
title: 中证500数据分析
description: 中证500指数成分股的多维度数据分析和可视化
baseurl: ""
url: ""

# 构建设置
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/

# 禁用 Jekyll 处理
include:
  - "*.html"
  - "*.js"
  - "*.css"
  - "*.png"
  - "*.jpg"

# 主题设置
theme: null